; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                  = 12250820-x86_64 MS Windows          
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = True                                
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
Labelled Sites                       = All Sites                           
Labels to Include                    =                                     
[ ProcessTypes ]
ppInfer                              = true                                
ppML                                 = true                                
[ AnalysisSettings ]
Analysis                             = Phylogeny Reconstruction            
Statistical Method                   = Maximum Likelihood                  
Phylogeny Test                       = ====================                
Test of Phylogeny                    = Standard Bootstrap (slow)           
Bootstrap Replicates                 = 1000                                
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = General Time Reversible model       
Rates and Patterns                   = ====================                
Rates among Sites                    = Gamma Distributed With Invariant Sites (G+I)
No of Discrete Gamma Categories      = 5                                   
Data Subset to Use                   = ====================                
Gaps/Missing Data                    = Use all sites                       
Select Codon Positions               = 1st, 2nd, 3rd, Non-Coding           
Tree Inference Options               = ====================                
ML Heuristic Method                  = Nearest-Neighbor-Interchange (NNI)  
Initial Tree for ML                  = Make initial tree automatically (Default - NJ/MP)
Branch Swap Filter                   = None                                
System Resource Usage                = ====================                
Number of Threads                    = 8                                   
Genetic Code Table                   = Not Applicable                      
Genetic Code                         = Not Applicable                      
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
